version: '2'

networks:
  neo4j-network:
    driver: bridge

services:
  neo4jc:
    image: bitnami/neo4j:3
    networks:
      - neo4j-network
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
